services:
  db:
    container_name: ${POSTGRES_HOSTNAME}
    hostname: ${POSTGRES_HOSTNAME}
    image: "${POSTGRES_IMAGE}"
    env_file:
      - ./env/postgresql.env
    ports:
      - "0.0.0.0:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 15s

  backend:
    container_name: ${USER_SERVICE_HOST_NAME}
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: ${USER_SERVICE_IMAGE}
    env_file:
      - ./env/postgresql.env
    hostname: ${USER_SERVICE_HOST_NAME}
    user: ${USER_SERVICE_HOST_NAME}
    ports:
      - "0.0.0.0:${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    cap_drop:
      - ALL
    deploy:
      mode: global
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 170M
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres:
