services:
  db:
    container_name: ${POSTGRES_HOSTNAME}
    hostname: ${POSTGRES_HOSTNAME}
    image: "postgres:${POSTGRES_TAG}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "0.0.0.0:${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 15s

  backend:
    container_name: user-service
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: user-service:latest
    env_file:
      - ./env/postgresql.env
    hostname: user-service
    user: user-service
    ports:
      - "127.0.0.1:8080:8080"
    cap_drop:
      - ALL
    deploy:
      mode: global
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 170M
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres:
