services:
  postgres12:
    container_name: postgres12
    hostname: postgres12
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres12:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  user-service:
    container_name: user-service
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: user-service:latest
    env_file:
      - ./env/postgresql.env
    hostname: user-service
    user: user-service
    ports:
      - "127.0.0.1:8080:8080"
    cap_drop:
      - ALL
    deploy:
      mode: global
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 170M

volumes:
  postgres12:
