server:
  port: ${USER_SERVICE_PORT:8080}
  servlet:
    context-path: ${API_PREFIX:/apiV1}

client:
  info:
    hostname: ${CLIENT_HOST_NAME:localhost}
    port: ${CLIENT_PORT:3000}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:animal_lovers}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
